<?php

// IMPORTAMOS EL ARCHIVO DE CONEXION A LA BD:

require 'includes/funciones.php';

// CREAMOS UNA VARIABLE PARA ENLAZARLA A LA FUNCIÓN QUE TRAE LOS DATOS DE LA BASE DE DATOS:

$servicios = obtenerServicios();


// PARA QUE EL NAVEGADOR (JS) PUEDA ENTENDER LOS DATOS QUE SE TRAEN DE UNA BASE DE DATOS, SE DEBE CONVERTIR EL ARRAY EN UN JSON:

echo json_encode($servicios);